name: Test Kai Service
on:
  pull_request:
    paths:
      - kai-service/**.py
      - kai-service/Containerfile
      - kai-service/requirements.txt
      - kai-service/tests/requirements.txt
  push:
    paths:
      - kai-service/**.py
      - kai-service/Containerfile
      - kai-service/requirements.txt
      - kai-service/tests/requirements.txt
  workflow_dispatch: {}

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@main
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: pushd kai-service && make deps && popd

      - name: Run test
        run: pushd kai-service && make test && popd

      - name: Build the Container
        id: build-image
        uses: redhat-actions/buildah-build@main
        with:
          image: kai-service
          tags: latest
          context: kai-service
          containerfiles: |
            ./kai-service/Containerfile
